# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - game-space

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: npm install and build project
              working-directory: ./frontend
              run: |
                  npm install
                  npm run build

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                    include-hidden-files: true
                    name: node-app
                    path: |
                        frontend/.next
                        frontend/package.json
                        frontend/package-lock.json
    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write #This is required for requesting the JWT

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Install dependencies and start app
              run: |
                npm ci

            - name: "Deploy to Azure Web App"
              uses: azure/webapps-deploy@v3
              id: deploy-to-webapp
              with:
                  app-name: "gamestore"
                  slot-name: 'Production'
                  publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE}}
                  package: .
            
            

