name: Build and deploy Node.js app to Azure Web App - gamspace

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            # Frontend: Install dependencies and build
            - name: Install frontend dependencies
              working-directory: ./frontend
              run: npm install

            - name: Build frontend
              working-directory: ./frontend
              run: npm run build --if-present

            - name: Verify build output
              run: ls -R ./frontend/.next # This will list all files in the .next directory for debugging

            # Upload the built artifacts to be used in the deployment job
            - name: Upload frontend build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: ./frontend/.next # This path should point to the build output

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write # This is required for requesting the JWT

        steps:
            # Download the previously uploaded artifact from the build job
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: build

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_40C5D69203174144BB78AE0868EA889D }}
                  tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_507D49C30D9C4A2F8858272DB886BF67 }}
                  subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_250BB598AA7447E6932A1C5E406E32EE }}

            - name: "Deploy to Azure Web App"
              uses: azure/webapps-deploy@v3
              id: deploy-to-webapp
              with:
                  app-name: "gamspace"
                  slot-name: "Production"
                  package: ./frontend/.next # Path to the build artifacts

            - name: Set startup command
              run: |
                  az webapp config set --name gamspace --resource-group demo --startup-file "node server.js"
